Bug#29003649 ROUTER FAILS BUILD AND REPORTS WARNINGS WITH CLANG7 ON WINDOWS
* fixed case libnames
* fixed compile-error on windows due to wrong type for socket

  error: non-constant-expression cannot be narrowed from type 'int' to
  'SOCKET' (aka 'unsigned long long') in initializer list
  [-Wc++11-narrowing]
        {sock, POLLOUT, 0},

* fixed wrong dllexports
* made message-check more resilent to localisation
  * error-msg may be localiced
  * error-msg may change with different CRT versions

* fixed const char * comparison with ==
* fixed clang-warning for RVO/std::move()
* explicitly define copy-constructor if destructor is declared

  * fixes clang-7 warning:

      definition of implicit copy assignment operator for
      'RandomGeneratorInterface' is deprecated because it has a user-declared
      destructor [-Wdeprecated]

* fixed format warning for DWORDs
* fixed error-msg handling on windows

    err_code was passed to get_last_error(), but then ignore. Instead
    GetLastError() was called all the time which may belong to another
    intemediate function-call that set the errno.

* removed unused code
* removed unused lambda captures

    warning: lambda capture 'this' is not used [-Wunused-lambda-capture]
* removed unused variable