Bug#36374232 read-write splitting fails with connector-j
When connector-j connects without "&trackSessionState=true" to the
read-write splitting port, updates may fail with:

java.sql.SQLException: Buffer length is less than expected payload
length.

Background
==========

The Ok-message for UPDATEs (or other commands) from the server may contain
a human-readable part like "Rows update: 1 ...".

When the client connects to the router without the CLIENT_SESSION_TRACK
capability, the Ok-message is wrongly encoded if it contains that
human-readable part.

Change
======

- encoded the human-readable part as "variable length string" instead of
  "string-to-the-end-of-packet" if CLIENT_SESSION_TRACK is not set.

Change-Id: I6160d8e4d6e600c57972b2c95d389c8b97706a9f